[package]
name = "gage-runtime2"
version.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
datafusion = { workspace = true }
gage-core = { path = "../gage-core" }
gage-query2 = { path = "../gage-query2" }
gage-runtime = { path = "../gage-runtime" }
gage-store = { path = "../gage-store" }
serde_json = { workspace = true }
tracing = { workspace = true }
percent-encoding = { workspace = true }
rune = { git = "https://github.com/gar1t/rune.git", branch = "gage" }
tokio = { workspace = true, features = ["rt", "sync", "macros"] }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
