[package]
name = "gage-scan"
version.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
chrono = { workspace = true }
codespan-reporting = "0.13.1"
gage-agent = { path = "../gage-agent" }
gage-claude = { path = "../gage-claude" }
gage-core = { path = "../gage-core" }
gage-db = { path = "../gage-db" }
gage-query = { path = "../gage-query" }
gage-registry = { path = "../gage-registry" }
gage-mcp = { path = "../gage-mcp" }
gage-runtime = { path = "../gage-runtime" }
num_cpus = { workspace = true }
petgraph = "0.6"
rune = { git = "https://github.com/gar1t/rune.git", branch = "gage" }
rune-modules = { git = "https://github.com/gar1t/rune.git", branch = "gage", features = ["time", "rand", "thread_rng"] }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync", "macros"] }
tokio-util = { workspace = true }
tracing = { workspace = true }

[[bench]]
name = "vm_lifecycle"
harness = false

[lints]
workspace = true
