[package]
name = "gage-scan2"
version.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
codespan-reporting = "0.13.1"
gage-core = { path = "../gage-core" }
gage-registry = { path = "../gage-registry" }
gage-runtime2 = { path = "../gage-runtime2" }
gage-scan = { path = "../gage-scan" }
gage-store = { path = "../gage-store" }
serde = { workspace = true }
serde_json = { workspace = true }
rune = { git = "https://github.com/gar1t/rune.git", branch = "gage" }
tokio = { workspace = true, features = ["rt", "sync", "macros"] }
tokio-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
