[default]

default = true
description = "Write summary using default file name"
exec = "python summary.py"
config = "summary.py"

[alt-summary-name]

description = "Write alternative summary file name"
exec = "SUMMARY=results.json python summary.py"
config = "summary.py"

[alt-summary-name.summary]

filename = "results.json"

[alt-summary-toml]

description = "Write alternative summary file as TOML"
exec = "SUMMARY=zefile.toml python summary.py"
env = { SUMMARY = "zefile.toml" } # What we'd like to do for Windows
config = "summary.py"

[alt-summary-toml.summary]

filename = "zefile.toml"

[alt-summary-metadata]

description = "Write summary vals with metadata"
exec = "python summary_metadata.py"

[output-summary]

description = "Use output to print summary"
exec = "python output_summary.py"

[output-summary-2]

description = "Alt of output-summary using default pattern"
exec = "python output_summary_2.py"

[output-summary-3]

description = "Alt of output summary using custom pattern"
exec = "python output_summary_3.py"
output-summary = "Summary:\n(.*?)\n\n"  # Use empty line as summary stop

[output-summary-4]

description = "Alt of output summary using invalid pattern"
exec = "python output_summary_2.py"
output-summary = "--- summary ---"
