[package]
name = "gage-cli"
version.workspace = true
edition.workspace = true
repository = "https://github.com/gageml/gage"

[[bin]]
name = "gage"
path = "src/main.rs"

[dependencies]
anyhow = "1"
chrono = { workspace = true }
gage-agent = { path = "../gage-agent" }
cliclack = "0.3"
clap = { version = "4", features = ["derive", "wrap_help"] }
datafusion = { workspace = true }
gage-core = { path = "../gage-core" }
gage-db = { path = "../gage-db" }
gage-test = { path = "../gage-test" }
gage-mcp = { path = "../gage-mcp" }
gage-tui = { path = "../gage-tui" }
gage-claude = { path = "../gage-claude" }
gage-index = { path = "../gage-index" }
gage-log = { path = "../gage-log" }
humantime = "2"
libc = "0.2"
notify = "8"
tabled = { version = "0.20", features = ["ansi"] }
textwrap = "0.16"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal"] }
tokio-util = "0.7"
console = "0.16.2"
pulldown-cmark = { version = "0.13", default-features = false }
serde_json = "1"
gage-query = { path = "../gage-query" }
gage-registry = { path = "../gage-registry" }
gage-scan = { path = "../gage-scan" }
gage-sync = { path = "../gage-sync" }
indicatif = "0.18"
num_cpus = "1"
rand = "0.9"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
toml.workspace = true

[lints]
workspace = true
