[package]
name = "gage-registry"
version.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
codespan-reporting = "0.13.1"
fs4 = { workspace = true }
gage-core = { path = "../gage-core" }
rune = { git = "https://github.com/gar1t/rune.git", branch = "gage" }
rust-embed = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
