name: Build

on:
  # push:
  #   branches: main

  workflow_dispatch:
    inputs:
      posix:
        description: Build for POSIX
        type: boolean
        default: true
      windows:
        description: Build for Windows
        type: boolean
        default: true
      release:
        description: Publish to PyPI (select for release)
        type: boolean
        default: false

jobs:
  build-posix:
    name: Build - POSIX
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.posix }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        python:
          - '3.10'
          - '3.11'
          - '3.12'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Build package
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip wheel --no-deps --wheel-dir dist .

      - name: Install package
        run: |
          python -m venv test-env
          test-env/bin/pip install --upgrade pip
          test-env/bin/pip install dist/*.whl
          test-env/bin/gage check

      - name: Install test requirements
        run: |
          test-env/bin/pip install groktest

      - name: Configure environment for tests
        # Git config required by tests that run git commands
        run: |
          git config --global user.name unused
          git config --global user.email unused@localhost
          git config --global init.defaultBranch main
          sudo apt install rclone -y || brew install rclone

      - name: Run tests
        env:
          CI: 1
          POSIX: 1
          GAGE_TEMPDIR: /tmp
        run: |
          test-env/bin/groktest .

  build-windows:
    name: Build - Windows
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.windows }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
        python:
          - '3.10'
          - '3.11'
          - '3.12'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Build package
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip wheel --no-deps --wheel-dir dist .

      - name: Install package
        run: |
          python -m venv test-env
          test-env\Scripts\pip install --upgrade pip
          pwsh -Command 'test-env\Scripts\pip install $(ls dist)'
          test-env\Scripts\gage check

      - name: Install test requirements
        run: |
          test-env\Scripts\pip install groktest

      - name: Install rclone
        run: |
          C:\msys64\usr\bin\wget.exe https://github.com/rclone/rclone/releases/download/v1.66.0/rclone-v1.66.0-windows-amd64.zip
          & "C:\Program Files\Git\usr\bin\unzip.exe" rclone-v1.66.0-windows-amd64.zip
          copy rclone-v1.66.0-windows-amd64\rclone.exe test-env\Scripts

      - name: Configure environment for tests
        run: |
          git config --global user.name unused
          git config --global user.email unused@localhost
          git config --global init.defaultBranch main

      - name: Run tests
        env:
          PYTHONUTF8: 1
          CI: 1
          WINDOWS: 1
          WINDOWS_FIX: 1
        run: |
          test-env\Scripts\activate
          groktest .

  publish-to-pypi:
    name: Publish to PyPI
    if: ${{ inputs.release }}
    needs:
      - build-posix
      - build-windows
    strategy:
      matrix:
        os:
          # Create dist on Linux
          - ubuntu-latest
        python:
          # Use oldest supported version of Python to create dist
          - '3.10'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python for build
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
